# Generated by Django 6.0.7 on 2026-07-29 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_professor_options_alter_aluno_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='users.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_aluno', to='principal.curso')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='principal.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='principal.materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='users.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlunoCurso', to='principal.alunocurso')),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MateriaCurso', to='principal.materiacurso')),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='principal.materiacurso')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='principal.matricula')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova', to='principal.prova')),
            ],
        ),
        migrations.AddConstraint(
            model_name='alunocurso',
            constraint=models.UniqueConstraint(fields=('aluno', 'curso'), name='unique_aluno_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='materiacurso',
            constraint=models.UniqueConstraint(fields=('curso', 'materia'), name='unique_materia_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='prova',
            constraint=models.UniqueConstraint(fields=('materia_curso', 'nome'), name='unique_nome_por_materia_curso'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('matricula', 'prova'), name='unique_matricula_por_prova'),
        ),
    ]
