# Generated by Django 4.2 on 2026-07-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_alunocurso_id_alter_curso_id_alter_materia_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prova',
            old_name='descricao',
            new_name='conteúdo',
        ),
    ]
