# Generated by Django 4.2 on 2026-07-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_aluno_id_alter_professor_id'),
        ('principal', '0003_rename_descricao_prova_conteúdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunocurso',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='users.aluno'),
        ),
        migrations.AlterField(
            model_name='alunocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='principal.curso'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='principal.curso'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='principal.materia'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='users.professor'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='principal.alunocurso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='principal.materiacurso'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='principal.matricula'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='principal.prova'),
        ),
    ]
