# Generated by Django 4.2 on 2026-07-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_aluno_id_alter_professor_id'),
        ('principal', '0004_alter_alunocurso_aluno_alter_alunocurso_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunocurso',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='users.aluno'),
        ),
        migrations.AlterField(
            model_name='alunocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_aluno', to='principal.curso'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='principal.curso'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='principal.materia'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='users.professor'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlunoCurso', to='principal.alunocurso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MateriaCurso', to='principal.materiacurso'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='principal.matricula'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova', to='principal.prova'),
        ),
    ]
