# Generated by Django 4.2 on 2026-07-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_alunocurso_aluno_alter_alunocurso_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='principal.alunocurso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='principal.materiacurso'),
        ),
    ]
