# Generated by Django 4.2 on 2026-07-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_professor_options'),
        ('principal', '0006_alter_matricula_aluno_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prova',
            old_name='conteúdo',
            new_name='conteudo',
        ),
        migrations.AlterField(
            model_name='alunocurso',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='users.aluno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='principal.matricula'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='principal.prova'),
        ),
    ]
