# Generated by Django 4.2 on 2026-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_rename_conteúdo_prova_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiacurso',
            name='formula_media',
            field=models.CharField(default='(N1*0,15)+(N2*0,15)+(N3*0,15)+(N4*0,55)', max_length=200),
        ),
    ]
