# Generated by Django 4.2 on 2026-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_materiacurso_formula_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiacurso',
            name='formula_media',
            field=models.CharField(max_length=200),
        ),
    ]
