# Generated by Django 4.2 on 2026-07-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_professor_options'),
        ('principal', '0009_alter_materiacurso_formula_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_curso', to='principal.curso'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='principal.materia'),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_lecionadas', to='users.professor'),
        ),
    ]
